### ISSUE TITLE
Please make tn.png the same as screenshot.png

### ISSUE THREAD

**Issue by onedrawingperday** [StaticMania/roxo-hugo#1]
Hello @kausarpial 

I am the other maintainer of Hugo Themes. Thank you for the Roxo theme.

However after seeing the theme on the list I noticed that tn.png features mock-ups that display how the theme looks in various resolutions along with a slogan.

However this custom layout does not look particularly good on mobile. 

The thumbnail should only show the theme layout as per the [guidelines](https://github.com/gohugoio/hugoThemes#media), so please make tn.png identical to screenshot.png.

Once you do this feel free to close this issue.

cc: @digitalcraftsman

**Comment by kausarpial** [comment]
Hi, @onedrawingperday 

Okay, I'll update the tn.png according to the guidelines.
Thanks for notifying that, It'll help us to the future submissions.
