### ISSUE TITLE
sudo git submodule add fatal fail

### ISSUE THREAD

**Issue by sebawrite** [StaticMania/roxo-hugo#11]
I can't install this theme submodule and I don't know why.

**Error Message:**
sudo git submodule add git@github.com:StaticMania/roxo-hugo.git themes/roxo
Cloning into '/var/www/html/sebawrite/themes/roxo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:StaticMania/roxo-hugo.git' into submodule path '/var/www/html/sebawrite/themes/roxo' failed

**Comment by kausarpial** [comment]
https://github.com/StaticMania/portio-hugo/issues/26#issuecomment-743710652
Hope that'd help you.

Thanks

**Comment by sebawrite** [comment]
As the advice says, I forked the repo and everything went smoothly from there on out.
