### ISSUE TITLE
Error: module "roxo-hugo" not found

### ISSUE THREAD

**Issue by kamesuke42** [StaticMania/roxo-hugo#25]
Thank you for creating a very nice theme.

When I tried to apply this theme following the instructions in the README, the following error occurred.

```
Error: module "roxo-hugo" not found; either add it as a Hugo Module or store it in "/path/to/project/themes".: module does not exist
```

Therefore, I rewrote config.toml as follows and it worked correctly.

```diff
+ theme         = "roxo"
- theme         = "roxo-hugo"
```

Which is correct, config.toml or readme?

**Comment by radovanovic-stevan** [comment]
Thanks for this man, had the same problem!
