### ISSUE TITLE
Overwrite components/_*.scss-files locally

### ISSUE THREAD

**Issue by janraasch** [StaticMania/roxo-hugo#7]
Hi there 👋🏻, 

first of all, thank you for this beautiful theme 🍦❤️.

I was wondering whether there is a way to overwrite particular `components/_*.scss` locally. So e.g. I made some changes to `partials/hero.html` and thus copied the `HTML`-template to my local `layouts`-directory. However, simply copying `assets/scss/components/_hero.scss` to my site root does not seem to work.

Any pointers are greatly appreciated.

Thank you & have a good weekend,
Jan

**Comment by kausarpial** [comment]
Hi Jan,

Which version of Hugo are you using?

**Comment by janraasch** [comment]
Hi there, thank you for the timely reply.

The latest one - I think - v0.74

Have a good Saturday 👋🏻

--

Jan Raasch
https://www.janraasch.com

On 29. August 2020 at 07:45:10, Kausar Ahmed (notifications@github.com) wrote:

Hi Jan,

Which version of Hugo are you using?

**Comment by kausarpial** [comment]
Don't copy the `resources` folder if your Hugo is the latest version.
If you did copy then remove the `resources` folder then run `hugo serve`.

Hope that'll resolve your problem, and you can work with the local scss files.

**Comment by janraasch** [comment]
So you would suggest to copy the whole assets/scss directory? I was hoping that I could only copy / overwrite the files I really want to change locally. 

I’ll check, if removing the resources-folder helps. Thank you very much.

**Comment by kausarpial** [comment]
Let's us know if you still face any problem

**Comment by janraasch** [comment]
Sure. Ty. I'll close this for now 👋 .

**Comment by janraasch** [comment]
Oh by the way, since it says

> A man who loves dog.

on your profile you might find this fun:

My girlfriend is using the `roxo-hugo` theme for her »nutritional counseling for dogs«-business 🐕  🐕‍🦺 😄 .

Here is a link to the first draft release of her new website, if you want to check it out:

https://hunde.isabellmartins.de

It's German... 😄 

Have a good Monday 👋 .

**Comment by kausarpial** [comment]
> Oh by the way, @kausarpial, since it says
> 
> > A man who loves dog.
> 
> on your profile you might find this fun:
> 
> My girlfriend is using the `roxo-hugo` theme for her »nutritional counseling for dogs«-business 🐕 🐕‍🦺 😄 .
> 
> Here is a link to the first draft release of her new website, if you want to check it out:
> 
> https://hunde.isabellmartins.de
> 
> It's German... 😄
> 
> Have a good Monday 👋 .

Haha :D

the website looks cool
