### ISSUE TITLE
netlify build command

### ISSUE THREAD

**Issue by sarishap** [StaticMania/roxo-hugo#8]
I was building this site in Netlify but couldn't deploy it. May I know the command for deploying the site?
![image](https://user-images.githubusercontent.com/59217956/93082350-7ffa2b80-f6b0-11ea-82e3-5a0401082ddb.png)

**Comment by kausarpial** [comment]
This isn't a starter. It's only the theme. You have to use the theme on your Hugo site first. You can deploy your site, not the theme.
